Update plugin section - user guide
WasmEdge/docs pull request #146
Opened 2023-08-14 06:44 UTC by mhmohona

## Explanation

Added plugin user guide for C, Rust and Go.

## Related issue- #85

## What type of PR is this
/kind documentation

2023-08-14 06:44 UTC, alabulei1 commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2023-08-16 10:41 UTC, mhmohona commented
@alabulei1 @q82419 I have completed working on this PR. Will you please have a look at it? 
Thank you!

2023-08-29 00:37 UTC, mhmohona commented on docs/embed/use-case/plugin/go_sdk.md
> +## Using Plug-ins to Extend the Runtime in C
@alabulei1, yes the other steps are almost same but the code is different for each plugin. 

Here is the reference:
- For C - [API reference](https://wasmedge.org/docs/embed/c/reference/latest#plug-ins)
- For Go - [API reference](https://wasmedge.org/docs/embed/go/reference/latest#plug-ins)
- For Rust - [Plugin Manager doc](https://wasmedge.github.io/wasmedge-rust-sdk/wasmedge_sdk/plugin/struct.PluginManager.html)

2023-09-01 03:32 UTC, q82419 requested changes

2023-09-01 05:17 UTC, mhmohona commented on docs/embed/use-case/plugin/go_sdk.md
> +## Using Plug-ins to Extend the Runtime in C
ops, sorry. My bad. I forgot to change this.

2023-09-11 18:36 UTC, q82419 requested changes

2023-09-11 18:36 UTC, q82419 commented on docs/embed/use-case/plugin/c_sdk.md
> +* The following API can retrieve the registered modules in the VM context,
Please actually lint the codes.

2023-09-12 18:35 UTC, q82419 approved these changes

2023-09-13 07:03 UTC, alabulei1 commented
I just released one question. Why this plugin guide located in embed section, not the extend section? @mhmohona

2023-09-13 07:58 UTC, mhmohona commented
> I just released one question. Why this plugin guide located in the Embed section, not the extend section? @mhmohona

@alabulei1, I was instructed to add the user guide here. cc: @q82419

2023-11-20 12:15 UTC, merged