Update the installation description for `wasmedge_rustls_plugin`
WasmEdge/docs pull request #176
Opened 2023-10-20 22:06 UTC by moznion

## Explanation

Starting with WasmEdge v0.13.4, the `wasmedge_rustls_plugin` has been bundled within the WasmEdge core (ref: https://github.com/WasmEdge/WasmEdge/releases/tag/0.13.4). Therefore, this patch modifies the installation instructions for rustls_plugin to indicate that it should be retrieved from the `WasmEdge/WasmEdge` repository, rather than from the `second-state/wasmedge_rustls_plugin`.

## Related issue

This might be related to #108

## What type of PR is this

> /kind documentation

2023-10-20 22:06 UTC, alabulei1 commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2023-10-21 12:57 UTC, adithyaakrishna commented
Looks good to me, @hydai Could you please review this PR? :)

2023-10-21 13:16 UTC, hydai requested changes

2023-10-21 13:16 UTC, hydai commented on docs/start/install.md
> +sudo cp libwasmedge_rustls /usr/local/lib/wasmedge/
The postfix is missed. `.so`.

2023-10-21 13:16 UTC, hydai commented on i18n/zh/docusaurus-plugin-content-docs/current/start/install.md
> +sudo cp libwasmedge_rustls /usr/local/lib/wasmedge/
Ditto.

2023-10-22 05:35 UTC, moznion commented
@hydai Thank you for pointing out. I corrected them at ec4fe3861f74ecd7f3b3e1120eb0d176dea7c60f.

2023-10-22 07:11 UTC, hydai approved these changes
Thanks

2023-10-22 07:11 UTC, merged