Remove TLS from install guide
WasmEdge/docs pull request #229
Opened 2024-05-24 08:37 UTC by juntao

## Explanation

Remove TLS Plugin from install docs

/kind documentation

2024-05-24 08:37 UTC, alabulei1 commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-05-24 09:55 UTC, alabulei1 commented
I don't think we should remove the rustTLS plugin directly because ome existing WasmEdge programs may depend on the rustTLS plugin. How about adding a special note for the RustTLS plugin?

2024-05-24 19:34 UTC, hydai requested changes

2024-05-25 07:46 UTC, juntao commented on docs/start/install.md
> +The Tensorflow Lite plugin is being deprecated from WasmEdge 0.14.0. We now compile TLS functions directly into Wasm for better portability.
done

2024-05-27 16:00 UTC, alabulei1 approved these changes

2024-05-27 16:25 UTC, hydai approved these changes

2024-05-27 16:25 UTC, merged