Added docs for Kubernetes+containerd+runwasi setup and updated runwasi setup
WasmEdge/docs pull request #240
Opened 2024-07-09 03:37 UTC by shiveshcodes

Signed-off-by: Shivesh Gupta <shiveshanjaligupta@gmail.com>
### Explanation
- Added docs for running Wasmedge in Kubernetes with containerd-shim-wasmedge using runwasi
- Updated the containerd+runwasi page with a line to run setup script for building runwasi
## Related issue
address #214 

## What type of PR is this

> /kind documentation
## Proposed Changes
Added instructions for running Wasmedge using runwasi with kubernetes and updated build instruction for runwasi

2024-07-09 03:37 UTC, alabulei1 commented
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-07-09 05:25 UTC, shiveshcodes commented
@CaptainVincent I would appreciate your feedback

2024-07-09 05:59 UTC, alabulei1 commented
Hi @shiveshcodes 

The DCO failed. Could you please check it out?

2024-07-09 06:13 UTC, shiveshcodes commented
I tried following the suggested steps to check that out besides my commit message has a Signed-off-by message. Am I missing something here ?

2024-07-09 06:30 UTC, shiveshcodes commented
@alabulei1 I have fixed the DCO issue, Sorry for the trouble.

2024-07-10 00:14 UTC, shiveshcodes commented
@alabulei1 @CaptainVincent A friendly reminder to review this code as and when you have time. Thank you

2024-07-10 18:16 UTC, hydai requested changes

2024-07-10 18:16 UTC, hydai commented on docs/develop/deploy/kubernetes/kubernetes-containerd-runwasi.md
> +
There are too many redundant lines.

2024-08-05 03:22 UTC, CaptainVincent commented
Verification done. No issues encountered. LGTM.

2024-08-05 06:09 UTC, hydai approved these changes

2024-08-05 06:09 UTC, merged