[Docs] Add MLX backend
WasmEdge/docs pull request #251
Opened 2024-09-09 04:42 UTC by grorge123

## Explanation

Add MLX install documentation.

## Related issue

[#3688](https://github.com/WasmEdge/WasmEdge/pull/3688)

## What type of PR is this

/kind documentation

2024-09-09 04:42 UTC, juntao commented
Hello, I am a [PR summary agent](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

2024-09-24 18:04 UTC, hydai requested changes

2024-09-24 18:04 UTC, hydai commented on docs/contribute/source/plugin/wasi_nn.md
> +Then you will have an executable `wasmedge` runtime under `/usr/local/bin` and the WASI-NN with MLX backend plug-in under `/usr/local/lib/wasmedge/libwasmedgePluginWasiNN.so` after installation.
Should it be `dylib` instead of `so`?

2024-09-25 06:25 UTC, hydai approved these changes

2024-09-25 06:27 UTC, merged